Add profile pages
stevensblueprint/aad-admin pull request #116
Opened 2024-02-20 17:05 UTC by nad2040

closes #21

Adds profile page under /profiles/[id] route.

2024-02-22 00:12 UTC, ulrokx requested changes
Looks good

2024-02-22 00:12 UTC, ulrokx commented on src/pages/profiles/[id].tsx
> +type ProfileProp = {
ButtonListProps

2024-02-22 00:12 UTC, ulrokx commented on src/pages/profiles/[id].tsx
> +const ButtonsList = (prop: ProfileProp) => {
you can destructure { profile }

2024-02-23 18:49 UTC, ulrokx commented on src/pages/profiles/[id].tsx
> +            sx={{
For clarification, tailwind styles means using classNames and tailwind classes.

2024-03-04 17:15 UTC, ShawnAviles commented
Need this to work on the Profile Editing screen @ulrokx. I can address the styling comments while working on #126.

2024-03-04 19:31 UTC, ulrokx approved these changes

2024-03-04 19:32 UTC, merged