Directory
stevensblueprint/aad-admin pull request #118
Opened 2024-02-20 23:25 UTC by juchen3637

2024-02-22 01:10 UTC, ulrokx requested changes
Nice job

2024-02-22 01:10 UTC, ulrokx commented on src/server/api/routers/user.ts
> +  getByRole: protectedProcedure.input(z.string()).query(async ({ input }) => {
It's a bit of a nit, but could we make this input an object with one field named role? Single object argument functions are pretty common with JS/TS and this function might want to take more arguments in the future (search, offset, limit)

2024-02-22 01:10 UTC, ulrokx commented on src/server/api/routers/user.ts
> +    return await db.profile.findMany({
Async functions return promises and tRPC will await any promise we return, so we don't need to await the promise returned by Prisma here before returning in this function. The behavior will be identical for both ways, with or without the await here, but we don't need the await so better to leave it out.

Thinking about it, depending on the JS runtime implementation, awaiting here might cost more memory as an intermediate promise object might be made here and resolved before returning. Either way you can drop the await and it still works. :D

2024-02-22 01:10 UTC, ulrokx commented on src/pages/directory.tsx
> +  const [current, setCurrent] = useState<string>("mentee");
We can use[ Typescript enums](https://www.typescriptlang.org/docs/handbook/enums.html#string-enums) to our advantage here. You can make the enum names all caps and make the strings the way you want to display it. You can use toUpperCase for the argument to useQuery.

https://stackoverflow.com/a/74326516

2024-02-22 01:10 UTC, ulrokx commented on src/pages/directory.tsx
> +      <ButtonGroup className="mb-4 mt-10" size="large" color="primary">
If these are tabs and there is a currently selected tab, maybe [this ToggleButton component](https://mui.com/material-ui/react-toggle-button/) is a better fit here?

2024-03-04 22:43 UTC, miguel-merlin commented
@ulrokx I didn't have time to look into the type inference with tRPC. Can we discuss it tomorrow? Also, build is failing because of problems with ```cp .env.example```

2024-03-12 15:04 UTC, miguel-merlin commented
@ulrokx Ready for review!

2024-03-12 15:12 UTC, miguel-merlin commented
#89

2024-03-14 22:21 UTC, ShawnAviles approved these changes
Looks good as long as @ulrokx approves of the follow-up changes. I have a PR coming that will need to edit some of this code (some new UI / Styling changes from working on #126); very minimal but hope to have this merged soon

2024-03-19 19:36 UTC, ulrokx approved these changes
👍

2024-03-19 19:36 UTC, ulrokx commented on src/utils/useProtectedPage.ts
> +  }, [session, router, roles]);
Nice

2024-03-19 19:36 UTC, merged