Feature/dashboard layout
stevensblueprint/aad-admin pull request #137
Opened 2024-03-04 03:42 UTC by miguel-merlin

## Description
Added the Admin layout component.

![image](https://github.com/stevensblueprint/aad-admin/assets/106508795/a959bb23-3fe1-473d-9827-79112496932a)

2024-03-04 03:46 UTC, miguel-merlin commented
Closes #119

2024-03-04 15:32 UTC, ulrokx requested changes
Nice

2024-03-04 15:32 UTC, ulrokx commented on src/components/layouts/AdminLayout.tsx
> +  const menuItems: MenuItem[] = [
Can we move this out of the function and into the module scope? If not this object will be created each render unnecessarily.

2024-03-04 15:32 UTC, ulrokx commented on src/components/layouts/AdminLayout.tsx
> +    await router.push(path);
Next router seems to return promises for some of these router methods but in all of their examples they don't await. I think this is fine here, although we might want to look at useTransition hook when this is hooked up to actual pages.

2024-03-04 15:32 UTC, ulrokx commented on src/components/layouts/AdminLayout.tsx
> +    <div style={{ display: "flex" }}>
There is nothing wrong with this but could we use Tailwind when possible? CSS in JS also has some performance downsides and by using Tailwind we avoid this potential slowdown and make the code consistent everywhere.

2024-03-04 15:32 UTC, ulrokx commented on src/components/layouts/AdminLayout.tsx
> +          "& .MuiDrawer-paper": {
Can you do this with Tailwind as well? Example https://mui.com/base-ui/guides/working-with-tailwind-css/#adding-an-interactive-slider-component

2024-03-05 17:37 UTC, ulrokx approved these changes
Great!

2024-03-05 17:39 UTC, merged