Feature/search sorting directory
stevensblueprint/aad-admin pull request #166
Opened 2024-03-26 05:48 UTC by miguel-merlin

#128

2024-04-01 20:27 UTC, ulrokx commented
Not sure if this is just me 
![image](https://github.com/stevensblueprint/aad-admin/assets/92767187/b4c7d236-9982-43c1-8b86-81ee240301ef)

2024-04-01 20:34 UTC, ulrokx requested changes
Looks good, just the types file

2024-04-01 20:34 UTC, ulrokx commented on @types/nextjs-routes.d.ts
> +    | StaticRoute<"/Directory">
Run `npx nextjs-routes` to regenerate this with lowercase

2024-04-09 19:40 UTC, miguel-merlin commented
Ready to merge

2024-04-09 22:19 UTC, ulrokx approved these changes

2024-04-09 22:19 UTC, merged