feat: Added routes to sidebar
stevensblueprint/aad-admin pull request #167
Opened 2024-03-26 06:10 UTC by miguel-merlin

#146

2024-04-01 20:50 UTC, ulrokx requested changes
See type changes, looks good!

2024-04-01 22:16 UTC, ShawnAviles commented
@miguel-merlin I also implemented routes in the Navbar Component if you wanna look at that as a reference #174

2024-04-09 19:34 UTC, miguel-merlin commented
Finally, ended up manually updating the routes

2024-04-10 14:43 UTC, ulrokx approved these changes

2024-04-10 14:45 UTC, merged