Stylize form page
stevensblueprint/aad-admin pull request #195
Opened 2024-04-16 16:37 UTC by phill52

closes #159

2024-04-16 20:35 UTC, ulrokx requested changes

2024-04-16 20:35 UTC, ulrokx commented on src/components/forms/JsonForm.tsx
> +        Fill out all the fields, and leave &quot;N/A&quot; for any that
I added an instructions field here https://github.com/stevensblueprint/aad-admin/pull/186 make sure this is showing if it isn't I forgot

2024-04-16 20:35 UTC, ulrokx commented on src/pages/form/[id].tsx
> +  } = api.collection.getSubmissions.useQuery({
A user shouldn't be able to call this query, only admins. Can we instead maybe do getSubmissionByCollectionId which a user can run if and only if the submission was submitted by them? If it returns null then the user hasn't filled out the form

2024-04-16 20:35 UTC, ulrokx commented on src/pages/form/[id].tsx
> +      router
just `void router.replace("/")`, it should never throw. it is async but we don't need to wait for it to run

2024-04-16 20:35 UTC, ulrokx commented on src/pages/form/[id].tsx
> +  if ((submitted || wasSubmitted) ?? user.status === "unauthenticated") {
This will create a timeout every time this component rerenders, put this in a useEffect or somewhere else

2024-04-16 20:35 UTC, ulrokx commented on src/pages/form/[id].tsx
> +      <div className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-midnight-sky to-aero">
We have this same outer div, so return something like

```tsx
<div className="...">
    {body}
</ div>
```

and do a `let body;` and set it in these ifs and have one return

2024-04-16 20:35 UTC, ulrokx commented on src/pages/form/[id].tsx
> +      <div className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-midnight-sky to-aero">
You can probably change them all into containers like on line 102 and and have one return

2024-04-25 02:19 UTC, ulrokx requested changes
Tiny thing and it's perfect

2024-04-25 02:19 UTC, ulrokx commented on src/components/forms/JsonForm.tsx
> +        don&apos;t apply to you.{" "}
Was this a mistake? can we not put everything in the backticks

2024-04-25 02:19 UTC, ulrokx commented on src/pages/form/[id].tsx
> +    userId: user?.data?.user?.id ?? "",
This should be accessed in the trpc handler, it doesn't need to be passed in. The ctx object in the trpc handler has access to this, take a look at some other routes.

2024-04-25 02:19 UTC, ulrokx commented on src/pages/form/[id].tsx
> +  } else if (data) {
Nice

2024-04-25 02:19 UTC, ulrokx commented on src/server/api/routers/collection.ts
> +    .query(async ({ input: { collectionId, userId } }) => {
I think ctx is a field like input here or it might be the second argument of the callback but it will give u the userid

2024-05-13 02:21 UTC, ulrokx commented
Taking over this PR

2024-05-13 02:23 UTC, phill52 commented
Go ahead, sorry been stuck with this end of semester crunch :(

2024-05-13 02:28 UTC, ulrokx commented
Hahaha no big deal just go easy on my web dev project :D

2024-05-13 04:38 UTC, merged