Admin Table
stevensblueprint/aad-admin pull request #204
Opened 2024-04-24 15:57 UTC by miguel-merlin

## Description
Added table to view users. You can delete and add new users.

2024-04-25 02:15 UTC, ulrokx requested changes

2024-04-25 02:15 UTC, ulrokx commented on docker-compose.yml
> -  panel:
oops

2024-04-25 02:15 UTC, ulrokx commented on docker-compose.yml
> -  panel:
i'm telling

2024-04-25 02:15 UTC, ulrokx commented on src/components/UserForm.tsx
> +    resolver: zodResolver(createUserSchema),
Niceeeeeeee

2024-04-25 02:15 UTC, ulrokx commented on src/pages/directory.tsx
> +          console.error("Failed to delete users:", error);
Is there a confirmation to delete users? If not we should probably have one - could be pretty damaging if done by accident. Also might mitigate prevent an error if the delete request goes through twice and the second one errors

2024-04-25 02:15 UTC, ulrokx commented on src/server/api/routers/user.ts
> +        return await db.user.create({
We should test this to make sure this works with google once we make google work

2024-04-25 02:15 UTC, ulrokx commented on src/server/api/routers/user.ts
> +            await prisma.user.delete({ where: { id } });
Can we cascade instead? Don't feel like we need to do it this way although nice job putting it into a transaction

2024-04-25 02:15 UTC, ulrokx commented on src/server/api/routers/user.ts
> +            await prisma.user.delete({ where: { id } });
If prisma supports soft delete we can look into that too to avoid accidents

2024-04-25 02:15 UTC, ulrokx commented on src/server/api/routers/user.ts
> -          message: '"{ctx.session.user.id}" not found in database',
Haha '"{ oops

2024-04-25 14:57 UTC, miguel-merlin commented on docker-compose.yml
> -  panel:
I'll take it out

2024-05-12 20:59 UTC, ulrokx commented
Taking over this PR

2024-05-12 22:33 UTC, ulrokx commented
https://github.com/stevensblueprint/aad-admin/pull/209

2024-05-12 22:33 UTC, closed without merging